### ISSUE TITLE
move injectorshell to ssh-mitm-plugins

### ISSUE THREAD

**Issue by manfred-kaiser** [The5imon/ssh-mitm-plugins#4]
We can move the injecotshell to ssh-mitm-plugins.

I want to implement only the core funcitons in ssh-mitm and all additional features should be moved out of ssh-mitm.

If it is okay for you, I will add "ssh-mitm-plugins" to the setup function in ssh-mitm as an optional dependency.

**Comment by The5imon** [comment]
Yes, lets do it this way.

**Comment by manfred-kaiser** [comment]
I have created a new release 0.4.1 of ssh-mitm. Now it is possible to install your plugins as an optional dependency.

```
pip install ssh-mitm[plugins]
```

You should add ssh-mitm to your setup file with 0.4.1 as min version, because in this release the injector shell is removed. I have created a pull request for this change.

**Comment by The5imon** [comment]
The injectorshell is now accommodated for by the ssh-mitm-plugins project. Pull requests #5 and #6 have implemented changes to do so. Version of ssh-mitm is now required to be 0.4.1 or higher.
